kind: pipeline
type: exec
name: ultimatebot

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - docker build -t ultimatebot .
  - name: cleanup dev
    commands:
      - docker stop ultimatebotdev || true
      - docker rm ultimatebotdev || true
  - name: deploy dev
    commands:
      - docker volume create ultimatedevvolume || true
      - docker run -d --name ultimatebotdev -v ultimatedevvolume:/app/data ultimatebot
  - name: cleanup prod
    commands:
      - docker stop ultimatebotprod || true
      - docker rm ultimatebotprod || true
  - name: deploy prod
    commands:
      - docker volume create ultimateprodvolume || true
      - docker run -d --name ultimatebotprod -v ultimateprodvolume:/app/data ultimatebot

trigger:
  branch:
    - master
  event:
    - push