kind: pipeline
type: exec
name: ultimatebot

platform:
  os: linux
  arch: amd64

steps:
  - name: build
    commands:
      - docker build -t ultimatebot .
  - name: cleanup
    commands:
      - docker stop ultimatebot || true
      - docker rm ultimatebot || true
  - name: deploy
    commands:
      - docker volume create ultimatebotvolume || true
      - docker run -d --name ultimatebot -v ultimatebotvolume:/app ultimatebot

trigger:
  branch:
    - master
  event:
    - push